#!/bin/bash

BIN=./bsq
mkdir -p tests_fscanf

make 2>/dev/null

run() {
    NAME="$1"
    FILE="$2"
    echo -e "\n--- $NAME ---"
    echo "Input:"
    cat "$FILE"
    echo -e "\nOutput:"
    $BIN "$FILE"
}

###############################################
# 1) ESPACES MULTIPLES ENTRE TOKENS
###############################################
cat > tests_fscanf/multi_spaces.txt << EOF
9      .     o     x
.....
.....
.....
.....
.....
.....
.....
.....
.....
EOF

###############################################
# 2) HEADER AVEC MOTS EN PLUS (fscanf l’accepte)
###############################################
cat > tests_fscanf/extra_words.txt << EOF
9 . o x pouet
.....
.....
.....
.....
.....
.....
.....
.....
.....
EOF

###############################################
# 3) HEADER AVEC ESPACE APRÈS LE FULL (fscanf l’accepte)
###############################################
cat > tests_fscanf/trailing_space.txt << EOF
9 . o x    
.....
.....
.....
.....
.....
.....
.....
.....
.....
EOF

###############################################
# 4) HEADER AVEC TABULATION (fscanf l’accepte)
###############################################
cat > tests_fscanf/tabs.txt << EOF
9\t.\to\tx
.....
.....
.....
.....
.....
.....
.....
.....
.....
EOF

###############################################
# 5) HEADER AVEC CARACTÈRE INVISIBLE (fscanf l’accepte)
###############################################
cat > tests_fscanf/invisible_char.txt << EOF
9 . o x$(printf '\r')
.....
.....
.....
.....
.....
.....
.....
.....
.....
EOF

###############################################
# 6) HEADER AVEC CARACTÈRE NON-PRINTABLE
###############################################
cat > tests_fscanf/non_printable.txt << EOF
9 . o $(printf '\x07')
.....
.....
.....
.....
.....
.....
.....
.....
.....
EOF

###############################################
# 7) HEADER AVEC ESPACE MANQUANT (fscanf l’accepte)
###############################################
cat > tests_fscanf/missing_space.txt << EOF
9 .ox
.....
.....
.....
.....
.....
.....
.....
.....
.....
EOF

###############################################
# 8) HEADER AVEC CHIFFRES COLLÉS (fscanf l’accepte)
###############################################
cat > tests_fscanf/sticky_numbers.txt << EOF
9.ox
.....
.....
.....
.....
.....
.....
.....
.....
.....
EOF

###############################################
# 9) HEADER AVEC NOMBRE TROP GRAND
###############################################
cat > tests_fscanf/overflow.txt << EOF
9999999999999999999999999999 . o x
.....
.....
EOF

###############################################
# 10) HEADER VIDE APRÈS ESPACES (fscanf l’accepte)
###############################################
cat > tests_fscanf/empty_after_spaces.txt << EOF
        9 . o x
.....
.....
.....
.....
.....
.....
.....
.....
.....
EOF

###############################################
# LANCEMENT DES TESTS
###############################################
for f in tests_fscanf/*.txt; do
    run "$(basename "$f")" "$f"
done

echo -e "\n=== FIN DES TESTS FSCANF FAIL ==="
